//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocPhi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class HeHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeHoc()
        {
            this.HocSinhs = new HashSet<HocSinh>();
            this.Lops = new HashSet<Lop>();
        }

        [Required(ErrorMessage = "Vui lòng nhập mã hệ học")]
        public string MaHeHoc { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên hệ học")]
        public string TenHeHoc { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập học phí")]
        public Nullable<double> HocPhi { get; set; }
        public string GhiChu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocSinh> HocSinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lops { get; set; }
    }
}
