//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocPhi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Lop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop()
        {
            this.HocSinhs = new HashSet<HocSinh>();
        }

        [Required(ErrorMessage = "Vui lòng nhập mã lớp học")]

        public string MaLop { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên lớp học")]
        public string TenLop { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn hệ học")]
        public string MaHeHoc { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn mã giáo viên ")]
        public string MaGiaoVien { get; set; }

        public string GhiChu { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập ngày bắt đầu")]

        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HeHoc HeHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocSinh> HocSinhs { get; set; }
    }
}
